"""empty message

Revision ID: 1fde35b67cd1
Revises: 3a11e7c4b039
Create Date: 2024-01-22 10:59:03.513679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fde35b67cd1'
down_revision = '3a11e7c4b039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
