"""Second migration -t

Revision ID: 4da7c452103c
Revises: edbed114d9bb
Create Date: 2024-01-31 16:20:11.303747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da7c452103c'
down_revision = 'edbed114d9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
