"""First migration

Revision ID: c429bcfaafad
Revises: 1fde35b67cd1
Create Date: 2024-01-22 11:46:16.485361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c429bcfaafad'
down_revision = '1fde35b67cd1'
branch_labels = None
depends_on = None


def upgrade():
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
